{
  "formatVersion": "1.1",
  "component": {
    "group": "net.spartanb312",
    "module": "genesis-kotlin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "genesis-kotlin-1.0.0.jar",
          "url": "genesis-kotlin-1.0.0.jar",
          "size": 85169,
          "sha512": "756a4fb946acdb08c9535ec85085317d59a2a819fa3ec6f093ea005549cc0f9d0d20a1e37b5c6053ff470f3ae5184b5b146913c634183b11188e8f3e9e2fd8ba",
          "sha256": "f7609b6b699fa7518498d416ad49f25920ff4f3763fbfc70ff4ece68eaa80876",
          "sha1": "b33549d9e576f78519891c4a83b6f980e66d7966",
          "md5": "bf41bd7d873c1590450748019c91d3ac"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib"
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "genesis-kotlin-1.0.0.jar",
          "url": "genesis-kotlin-1.0.0.jar",
          "size": 85169,
          "sha512": "756a4fb946acdb08c9535ec85085317d59a2a819fa3ec6f093ea005549cc0f9d0d20a1e37b5c6053ff470f3ae5184b5b146913c634183b11188e8f3e9e2fd8ba",
          "sha256": "f7609b6b699fa7518498d416ad49f25920ff4f3763fbfc70ff4ece68eaa80876",
          "sha1": "b33549d9e576f78519891c4a83b6f980e66d7966",
          "md5": "bf41bd7d873c1590450748019c91d3ac"
        }
      ]
    }
  ]
}
