{
  "formatVersion": "1.1",
  "component": {
    "group": "net.spartanb312",
    "module": "genesis-java",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "genesis-java-1.0.0.jar",
          "url": "genesis-java-1.0.0.jar",
          "size": 18465,
          "sha512": "0dbd2f0bbad89aa263e272dc52c0ea34e948633d4e078e4a010790ee871dce080d1cf4aa8f7bd6efa1950e8c721532d1fb517e632d2eea2b3d7c817c16312917",
          "sha256": "cd11a242fd58df04bf41d5ad250c2ea722a4b52d11888812ba2610a0afdb02bd",
          "sha1": "45fd9e03090615d49ff9c17878c93ccc44aad75e",
          "md5": "ccfb703407c3b113b75b2ffc5db7ed8b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "genesis-java-1.0.0.jar",
          "url": "genesis-java-1.0.0.jar",
          "size": 18465,
          "sha512": "0dbd2f0bbad89aa263e272dc52c0ea34e948633d4e078e4a010790ee871dce080d1cf4aa8f7bd6efa1950e8c721532d1fb517e632d2eea2b3d7c817c16312917",
          "sha256": "cd11a242fd58df04bf41d5ad250c2ea722a4b52d11888812ba2610a0afdb02bd",
          "sha1": "45fd9e03090615d49ff9c17878c93ccc44aad75e",
          "md5": "ccfb703407c3b113b75b2ffc5db7ed8b"
        }
      ]
    }
  ]
}
