{
  "formatVersion": "1.1",
  "component": {
    "group": "net.spartanb312",
    "module": "genesis-java",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "genesis-java-1.0.jar",
          "url": "genesis-java-1.0.jar",
          "size": 18465,
          "sha512": "60e21355ab4ce67a86b68b5a2526d2c1987ec043664592331bd8543921e993e51d6c1c6e808edc369d4f1422358e7fcef61b6c53529dfcfac74412ab2b1099e2",
          "sha256": "a46ea855492ff9e3c55c0d131267f477c7cab63ebb58e4500c07018e9e8733ee",
          "sha1": "c8e6a3f68410b72f2107f4a41070d127d8dfe068",
          "md5": "fd41aa16618acb90f62e06b671ae91cb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "genesis-java-1.0.jar",
          "url": "genesis-java-1.0.jar",
          "size": 18465,
          "sha512": "60e21355ab4ce67a86b68b5a2526d2c1987ec043664592331bd8543921e993e51d6c1c6e808edc369d4f1422358e7fcef61b6c53529dfcfac74412ab2b1099e2",
          "sha256": "a46ea855492ff9e3c55c0d131267f477c7cab63ebb58e4500c07018e9e8733ee",
          "sha1": "c8e6a3f68410b72f2107f4a41070d127d8dfe068",
          "md5": "fd41aa16618acb90f62e06b671ae91cb"
        }
      ]
    }
  ]
}
