{
  "formatVersion": "1.1",
  "component": {
    "group": "net.spartanb312",
    "module": "genesis-scala",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "genesis-scala-1.0.jar",
          "url": "genesis-scala-1.0.jar",
          "size": 104069,
          "sha512": "1a1be57174689b1cf273c508316618aa1cba94ddea31fb101ec83d2f34612338377e2e4591099421d3caaf34ddffa7cfcaf33ad2ed647607fec2e5372914b969",
          "sha256": "c8026b90afc76392e16df06c271550a8483d3ba57027c15fe0ad994215394219",
          "sha1": "5d6139887ce18d02f8f456c6d2c97faf177fe130",
          "md5": "3d21f9313c6daa3be5e598e9cdda7773"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.scala-lang",
          "module": "scala3-library_3",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "genesis-scala-1.0.jar",
          "url": "genesis-scala-1.0.jar",
          "size": 104069,
          "sha512": "1a1be57174689b1cf273c508316618aa1cba94ddea31fb101ec83d2f34612338377e2e4591099421d3caaf34ddffa7cfcaf33ad2ed647607fec2e5372914b969",
          "sha256": "c8026b90afc76392e16df06c271550a8483d3ba57027c15fe0ad994215394219",
          "sha1": "5d6139887ce18d02f8f456c6d2c97faf177fe130",
          "md5": "3d21f9313c6daa3be5e598e9cdda7773"
        }
      ]
    }
  ]
}
