{
  "formatVersion": "1.1",
  "component": {
    "group": "net.spartanb312",
    "module": "genesis-scala",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "genesis-scala-1.0.0.jar",
          "url": "genesis-scala-1.0.0.jar",
          "size": 104069,
          "sha512": "27ec1db8984b3a55d951059357bd4fb924da493b0a53f4f93572bb65337ff65edb19cf4304685bc70bc4c88140ec4918e622a35015c651e65987546ee507603c",
          "sha256": "992c1ff8a1bc5ead002a4255711162ce0a9296884264b68d9e5ffe6ce1b123a4",
          "sha1": "82244785028de38790600505d40cd7684fe92530",
          "md5": "ad14841779fea9c0cfbcdbf2492478a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.scala-lang",
          "module": "scala3-library_3",
          "version": {
            "requires": "3.6.3"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-tree",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-analysis",
          "version": {
            "requires": "9.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.21"
          }
        }
      ],
      "files": [
        {
          "name": "genesis-scala-1.0.0.jar",
          "url": "genesis-scala-1.0.0.jar",
          "size": 104069,
          "sha512": "27ec1db8984b3a55d951059357bd4fb924da493b0a53f4f93572bb65337ff65edb19cf4304685bc70bc4c88140ec4918e622a35015c651e65987546ee507603c",
          "sha256": "992c1ff8a1bc5ead002a4255711162ce0a9296884264b68d9e5ffe6ce1b123a4",
          "sha1": "82244785028de38790600505d40cd7684fe92530",
          "md5": "ad14841779fea9c0cfbcdbf2492478a4"
        }
      ]
    }
  ]
}
